### ISSUE TITLE
Thống nhất về công nghệ sẽ sử dụng

### ISSUE THREAD

**Issue by Natashi402** [Natashi402/AutoImageTagSuggestionSE02#1]
Hiện tại nhóm chúng ta sẽ thực hiện một ứng dụng web có thể tự đưa ra các gợi ý về tag cho người dùng facebook, instagram và twitter. Trong issue này ta sẽ thống nhất về việc sử dụng công nghệ nào cho bài tập nhóm này.

**Comment by cd2012hn** [comment]
Các bạn định sử dụng những công nghệ nào ạ?

**Comment by Natashi402** [comment]
Hiện tại tôi nghĩ nên viết trên framework laravel

**Comment by H3D-MinhNTC** [comment]
mình nghĩ nên sử dụng Slim cho nhẹ

**Comment by cd2012hn** [comment]
Minh có thể giải thích lý do dùng slim không? Nếu bảo nhẹ thì có hơi... không rõ ràng

**Comment by H3D-MinhNTC** [comment]
> Minh có thể giải thích lý do dùng slim không? Nếu bảo nhẹ thì có hơi... không rõ ràng

slim framework là một micro framework của PHP nên nó khá là nhẹ so với các bộ framework khác, tuy là nó chỉ thích hợp dùng cho các dự án nhỏ tuy nhiên nó vẫn cung cấp khá đầy đủ những chức năng cần thiết

**Comment by cd2012hn** [comment]
Giải thích như sgk thế bạn :( Về cơ bản thì Slim vì nó nhỏ gọn, dễ triển khai nên khá thích hợp để làm những dự án nhỏ, và thường thì dùng để viết API hoặc UI đợn giản. Giờ mình cần phải xem xem liệu dự án của mình có nên sử dụng một thứ hoàn toàn mới không như thế, hay ngắn gọn là: nó có đáng không?

**Comment by nguyenthocongminh** [comment]
mình nghĩ nên sử dụng Slim cho nhẹ

**Comment by Natashi402** [comment]
Như anh Nguyên cũng nói trên lớp thì hiện tại laravel là một framework khá mạnh, dễ cài đặt và có cộng đồng lớn nên tôi nghĩ làm laravel thì sẽ không gặp nhiều vấn đề với những thứ mình định làm

**Comment by cd2012hn** [comment]
Giải thích như sgk thế bạn :( Về cơ bản thì Slim vì nó nhỏ gọn, dễ triển khai nên khá thích hợp để làm những dự án nhỏ, và thường thì dùng để viết API hoặc UI đợn giản. Giờ mình cần phải xem xem liệu dự án của mình có nên sử dụng một thứ hoàn toàn mới không như thế, hay ngắn gọn là: nó có đáng không?

**Comment by H3D-MinhNTC** [comment]
slim framework là một micro framework của PHP nên có vẻ nó khá là nhẹ so với các bộ framework khác, tuy là nó chỉ thích hợp dùng cho các dự án nhỏ tuy nhiên nó vẫn cung cấp khá đầy đủ những chức năng cần thiết

Ngoài ra nó cũng hỗ trợ khá tốt trong việc tạo ra RESTful APIs và dịch vụ cái mà chúng ta đang cần

**Comment by cd2012hn** [comment]
Còn laravel thì cộng đồng nó hiện làm một trong những cộng đồng lớn nhất trong bọn php framework, có các issue chỉ cần đặt câu hỏi thôi là sẽ có người trả lời gần như lập tức

**Comment by nguyenthocongminh** [comment]
> Minh có thể giải thích lý do dùng slim không? Nếu bảo nhẹ thì có hơi... không rõ ràng

slim framework là một micro framework của PHP nên nó khá là nhẹ so với các bộ framework khác, tuy là nó chỉ thích hợp dùng cho các dự án nhỏ tuy nhiên nó vẫn cung cấp khá đầy đủ những chức năng cần thiết

Ngoài ra nó cũng hỗ trợ khá tốt trong việc tạo ra RESTful APIs và dịch vụ cái mà chúng ta đang cần

**Comment by nguyenthocongminh** [comment]
slim framework là một micro framework của PHP nên mình nghĩ nó khá là nhẹ so với các bộ framework khác, tuy là nó chỉ thích hợp dùng cho các dự án nhỏ tuy nhiên nó vẫn cung cấp khá đầy đủ những chức năng cần thiết

Ngoài ra nó cũng hỗ trợ khá tốt trong việc tạo ra RESTful APIs và dịch vụ cái mà chúng ta đang cần

**Comment by nguyenthocongminh** [comment]
vậy thì dùng laravel đi, nó khá là mạnh và cũng không phức tạp lắm, mà mình cũng không chắc là dù Slim nhẹ tuy nhiên mình cũng chưa quen với nó lắm, dùng một thứ mới thế có hơi mạo hiểm thật

**Comment by Natashi402** [comment]
Vậy chúng ta sẽ thống nhất dùng laravel để làm web
Vấn đề tiếp theo là nên viết cái xử lý gợi ý tag bằng ngôn ngữ nào. Hiện tại có 2 ngôn ngữ xử lý tốt là python và C++ 
Các bạn chọn đi nào

**Comment by cd2012hn** [comment]
tôi thống nhất dùng laravel, còn về phần xử lý tag thì theo t tìm hiểu, nếu mình học máy thì nên dùng python.

**Comment by cd2012hn** [comment]
chứ c++ thì nó hơi hardmode quá 😢

**Comment by cd2012hn** [comment]
về cơ bản thì python cũng chỉ là gọi xuống các thư viện C/C++ thôi mà

**Comment by H3D-MinhNTC** [comment]
mình cũng nghĩ dùng python thì dễ hơn là C, C thì hình như hướng lập trình ứng dụng nhiều hơn, mà tuy python chậm hơn C++ cơ mà cấu trúc nó đơn giản hơn

**Comment by nguyenthocongminh** [comment]
mình cũng nghĩ dùng python thì dễ hơn là C, C thì hình như hướng lập trình ứng dụng nhiều hơn, mà tuy python chậm hơn C++ cơ mà cấu trúc nó đơn giản hơn

**Comment by Natashi402** [comment]
Hiện tại tôi cũng đang nghiêng về python hơn bởi vì bộ thư viện hỗ trợ nhiều và cú pháp đơn giản

**Comment by cd2012hn** [comment]
vậy tôi đoán là chúng ta đã thống nhất được rồi đúng không ? =))

**Comment by Natashi402** [comment]
bạn còn chưa cho ý kiến mà bạn

**Comment by cd2012hn** [comment]
t bảo mình nên dùng python rồi mà 😢 oan cho t quá

**Comment by Natashi402** [comment]
OK vậy chúng ta thống nhất sẽ dùng kết hợp laravel và python cho dự án này
